version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  npm-install:
    executor: node/default
    steps:
      - node/install-packages:
          cache-path: ~/project/node_modules
  test:
    executor: node/default
    steps:
      - run:
          command: npm run test
workflows:
  setup:
    jobs:
      - npm-install
  test:
    jobs:
      - test
