version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  Do-npm-install:
    executor: node/default
    steps:
      - node/install-packages:
          app-dir: ../
          cache-path: ~/node_modules
workflows:
  setup:
    jobs:
      - Do-npm-install
