version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  Do npm-install:
    executor: node/default
    steps:
      - node/install-packages:
          app-dir: ~/
          cache-path: ~/node_modules
  Run-tests:
    executor: node/test
    steps:
      - run:
          command: npm run test
workflows:
  setup:
    jobs:
      - npm-install
  test:
    jobs:
      - test
